# Generated by Django 6.0.6 on 2026-08-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0010_existinginsurancecover_policy_number_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
